// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDeletedUser = "deleted_users"

// DeletedUser mapped from table <deleted_users>
type DeletedUser struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Name      string         `gorm:"column:name" json:"name"`
	Gender    string         `gorm:"column:gender" json:"gender"`
}

// TableName DeletedUser's table name
func (*DeletedUser) TableName() string {
	return TableNameDeletedUser
}
