// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserinfo = "userinfos"

// Userinfo mapped from table <userinfos>
type Userinfo struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name   string `gorm:"column:name;default:jack" json:"name"`
	Gender string `gorm:"column:gender" json:"gender"`
}

// TableName Userinfo's table name
func (*Userinfo) TableName() string {
	return TableNameUserinfo
}
