package main

func main() {
	// fmt.Println("hello world!")
	// mapTest()
	// MapSlice()
	// sliceMap()
	// wordcount("how do you do")
	// test()
	// funtionTest()
	// intSum(1, 2, 3, 4, 5, 6)
	// a, b := calc(2, 3)
	// fmt.Println(a, b)
	// funcVariable()
	// main()
	// NoNameFunc()
	// Closure()
	// defertest()
	// panicTest()
	// main3()
	// Addr1()
	// Mem()
	// MakeTest()
	// type1()
	// structTest()
	// interview1()
	// ConstructTest()
	// CombineStruct()
}
